export const GETMSGS_SUCCESS = "GETMSGS_SUCCESS";
export const GETMSGS_FAILED = "GETMSGS_FAILED";
export const GETMSGS_LOADING = "GETMSGS_LOADING";
export const SENDMSG = "SENDMSG";

export const GET_COMMENTS_SUCCESS = "GET_COMMENTS";
export const GET_COMMENTS_FAILED = "GET_COMMENTS_FAILED";
export const GET_COMMENTS_LOADING = "GET_COMMENTS_LOADING";
export const UPDATE_COMMENTS = "UPDATE_COMMENTS";
